# -*- coding: utf-8 -*-
"""ML_Practical2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NpMXeXH1OPeiy0QaVQh5hxZEqLKZ88Z_
"""

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

#Step 1: Load Real Dataset
housing = fetch_california_housing()

#convert to dataframe
df = pd.DataFrame(housing.data, columns=housing.feature_names)
df['target'] = housing.target

print(df.head())

df.shape

df.describe()

df.info()

#step2: Feature & Target Split
x=df.drop('target',axis=1)
y=df['target']

x.head()

y.head()

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

x_train.shape

x_test.shape

y_train.shape

y_test.shape

#step 4: Train Linear Regression Model
model=LinearRegression()
model.fit(x_train,y_train)

#step 5: Prediction
y_pred=model.predict(x_test)

#step 6:Model Evaluation
import numpy as np

mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
rmse=np.sqrt(mse)
r2=r2_score(y_test,y_pred)

print(f"\n Model Evaluation Matrices:")
print(f"Mean Absolute Error (mae):{mae}")
print(f"Mean Squared Error (mse):{mse}")
print(f"Root Mean Squared Error (rmse):{rmse}")
print(f"R squared Score(R2):{r2}")

plt.scatter(x_test['MedInc'], y_test, label='Actual Values')
plt.scatter(x_test['MedInc'], y_pred, label='Predicted Values')
plt.xlabel('MedInc')
plt.ylabel('House Value')
plt.title('Linear Regression on California Housing Dataset')
plt.legend()
plt.show()